# Generated by Django 5.2.7 on 2026-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Vitamin', 'Vitamin'), ('Mineral', 'Mineral'), ('Supplement', 'Supplement')], max_length=20)),
                ('dosage', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('side_effects', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
